# Postgres Config
spring.profiles.active=prod
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5433/book
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Swagger
app.server.url=http://localhost:9099


# Email
spring.mail.username=
spring.mail.password=
spring.mail.from=
spring.mail.properties.mail.smtp.from=

spring.mail.protocol=smtp
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


# Logging
logging.level.org.springframework.cache=TRACE
spring.jmx.enabled=false
logging.level.root=INFO